version: 2

models:
  - name: stg_stock_prices
    columns:
      - name: ticker
        tests:
          - not_null
      - name: close_price
        tests:
          - not_null

  - name: stg_crypto_prices
    columns:
      - name: coin
        tests:
          - not_null
      - name: price_usd
        tests:
          - not_null
